# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - emoji-search

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://azurecloudweek.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2a4cd82739fd456ab7fed19125a42efd }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8acdb9f0caad4f7a8c76cb64762ed7e3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: azurecloudweek.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2a4cd82739fd456ab7fed19125a42efd }}/emojisearch:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'emoji-search'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_55542225b65043cdb6f2d38825221857 }}
        images: 'azurecloudweek.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2a4cd82739fd456ab7fed19125a42efd }}/emojisearch:${{ github.sha }}'